Fix panic in fuzzy-select when using non-ASCII characters
console-rs/dialoguer pull request #245
Opened 2023-02-22 08:56 UTC by stormshield-kg

Use the [`str::char_indices()`](https://doc.rust-lang.org/std/primitive.str.html#method.char_indices) to keep valid byte offsets in memory.

Also add handling of  the `Delete` key.

2023-09-05 20:24 UTC, Gordon01 commented
I tested this PR and it indeed fixes the problem with non-ASCII characters. 

However, I believe that `format_fuzzy_select_prompt()` may be the only one that needs to be fixed to correctly support UTF-8.
Specifically replace indexing with `.chars()` method as described here: https://stackoverflow.com/questions/48642342/how-to-get-the-last-character-of-a-str

2023-09-05 20:29 UTC, Gordon01 commented on src/prompts/fuzzy_select.rs
> +        let mut char_index = position_indices.len() - 1;
A correct iteration over chars should be used in rendering instead.
As described here: https://stackoverflow.com/questions/24542115/how-to-index-a-string-in-rust

2023-09-05 20:31 UTC, Gordon01 requested changes
Thanks for this PR

2023-09-06 09:10 UTC, stormshield-kg commented on src/prompts/fuzzy_select.rs
> +        let mut char_index = position_indices.len() - 1;
With the `.chars()` iterator, you cannot go the left of a string, only to the right. I used a `Vec` of char indices in order to be able to remove a letter in the middle of the text, if the cursor is not at the end.

2023-09-08 19:16 UTC, Gordon01 commented
I believe we don't need an optimization for `search_term` indexes. 
It's small (will fin into the L1 cache) so recalculating it in a loop will not affect performance, but it makes the code simpler.

<details><summary>Details</summary>
<p>

```diff
diff --git a/src/prompts/fuzzy_select.rs b/src/prompts/fuzzy_select.rs
index 39824be..3f83947 100644
--- a/src/prompts/fuzzy_select.rs
+++ b/src/prompts/fuzzy_select.rs
@@ -195,18 +195,9 @@ impl FuzzySelect<'_> {
 
     fn _interact_on(self, term: &Term, allow_quit: bool) -> Result<Option<usize>> {
         // Place cursor at the end of the search term
-        let mut bytes_position = self.initial_text.len();
+        let mut cursor = self.initial_text.chars().count();
         let mut search_term = self.initial_text.to_owned();
 
-        let mut position_indices = search_term
-            .char_indices()
-            .map(|(index, _)| index)
-            .collect::<Vec<_>>();
-
-        position_indices.push(search_term.len());
-
-        let mut char_index = position_indices.len() - 1;
-
         let mut render = TermThemeRenderer::new(term, self.theme);
         let mut sel = self.default;
 
@@ -233,8 +224,14 @@ impl FuzzySelect<'_> {
         let mut vim_mode = false;
 
         loop {
+            let mut byte_indices = search_term
+                .char_indices()
+                .map(|(index, _)| index)
+                .collect::<Vec<_>>();
+            byte_indices.push(search_term.len());
+
             render.clear()?;
-            render.fuzzy_select_prompt(self.prompt.as_str(), &search_term, bytes_position)?;
+            render.fuzzy_select_prompt(self.prompt.as_str(), &search_term, byte_indices[cursor])?;
 
             // Maps all items to a tuple of item and its match score.
             let mut filtered_list = self
@@ -313,16 +310,14 @@ impl FuzzySelect<'_> {
                     }
                     term.flush()?;
                 }
-                (Key::ArrowLeft, _, _) | (Key::Char('h'), _, true) if char_index > 0 => {
-                    char_index -= 1;
-                    bytes_position = position_indices[char_index];
+                (Key::ArrowLeft, _, _) | (Key::Char('h'), _, true) if cursor > 0 => {
+                    cursor -= 1;
                     term.flush()?;
                 }
                 (Key::ArrowRight, _, _) | (Key::Char('l'), _, true)
-                    if char_index < position_indices.len() - 1 =>
+                    if cursor < byte_indices.len() - 1 =>
                 {
-                    char_index += 1;
-                    bytes_position = position_indices[char_index];
+                    cursor += 1;
                     term.flush()?;
                 }
                 (Key::Enter, Some(sel), _) if !filtered_list.is_empty() => {
@@ -342,44 +337,18 @@ impl FuzzySelect<'_> {
                     term.show_cursor()?;
                     return Ok(sel_string_pos_in_items);
                 }
-                (Key::Backspace, _, _) if char_index > 0 => {
-                    let old_position = bytes_position;
-
-                    char_index -= 1;
-                    bytes_position = position_indices[char_index];
-
-                    let char_len = old_position - bytes_position;
-                    position_indices.remove(char_index);
-                    for index in &mut position_indices[char_index..] {
-                        *index -= char_len;
-                    }
-
-                    search_term.replace_range(bytes_position..old_position, "");
+                (Key::Backspace, _, _) if cursor > 0 => {
+                    cursor -= 1;
+                    search_term.remove(byte_indices[cursor]);
                     term.flush()?;
                 }
-                (Key::Del, _, _) if char_index < position_indices.len() - 1 => {
-                    let char_len = position_indices[char_index + 1] - bytes_position;
-                    position_indices.remove(char_index + 1);
-
-                    for index in &mut position_indices[char_index + 1..] {
-                        *index -= char_len;
-                    }
-
-                    search_term.replace_range(bytes_position..bytes_position + char_len, "");
+                (Key::Del, _, _) if cursor < byte_indices.len() - 1 => {
+                    search_term.remove(byte_indices[cursor]);
                     term.flush()?;
                 }
                 (Key::Char(chr), _, _) if !chr.is_ascii_control() => {
-                    let char_len = chr.len_utf8();
-                    let old_position = bytes_position;
-                    bytes_position += char_len;
-                    position_indices.insert(char_index, old_position);
-
-                    char_index += 1;
-                    for index in &mut position_indices[char_index..] {
-                        *index += char_len;
-                    }
-
-                    search_term.insert(old_position, chr);
+                    search_term.insert(byte_indices[cursor], chr);
+                    cursor += 1;
                     term.flush()?;
                     sel = Some(0);
                     starting_row = 0;

```  

</p>
</details>

2023-09-08 19:24 UTC, Gordon01 requested changes
Please consider the attached diff.

Also, please update the changelog.

2023-09-08 19:24 UTC, Gordon01 commented on src/prompts/fuzzy_select.rs
> +                    search_term.replace_range(bytes_position..bytes_position + char_len, "");
We should put indexes recalculation in a loop and ditch this code.
I believe that it's an unnecessary optimisation since `search_term` is tiny but it complicates those functions a lot.

2023-09-08 19:24 UTC, Gordon01 commented on src/theme/colorful.rs
> +            write!(f, "{prompt_prefix} {styled_prompt} ")?;
Those bindings aren't used anywhere else. Let's leave this code intact.

2023-09-08 19:33 UTC, Gordon01 commented
Just realized that `Input` builds a `Vec` of chars. That's also a way for code simplification. https://github.com/console-rs/dialoguer/blob/master/src/prompts/input.rs#L321

2023-09-09 16:52 UTC, Gordon01 commented
Let's add Delete key handling to Input too, since it also lacks this functionality.

2023-09-11 15:03 UTC, Gordon01 commented on CHANGELOG.md
> +* Add handling of Delete key for fuzzy-select
Use `FuzzySelect` instead of fuzzy-select

2023-09-11 15:04 UTC, Gordon01 approved these changes
Looks great, thank you!

2023-09-11 18:28 UTC, Gordon01 reviewed
LGTM

2023-09-11 18:33 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +                    if cursor < byte_indices.len() - 1 =>
I haven't tried it locally but is the `-1` needed?

2023-09-11 18:33 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +                (Key::Del, _, _) if cursor < byte_indices.len() - 1 => {
Same question about `-1`.

2023-09-11 18:33 UTC, pksunkara commented on src/theme/mod.rs
> +        bytes_pos: usize,
This is a breaking change that needs to be talked about in the changelog.

2023-09-11 21:08 UTC, Gordon01 commented on src/prompts/fuzzy_select.rs
> +                    if cursor < byte_indices.len() - 1 =>
Yes, because byte_indices contains one additional element: `byte_indices.push(search_term.len());`

2023-09-11 21:08 UTC, Gordon01 commented on src/prompts/fuzzy_select.rs
> +                (Key::Del, _, _) if cursor < byte_indices.len() - 1 => {
Same here

2023-09-11 21:11 UTC, Gordon01 commented on src/theme/mod.rs
> +        bytes_pos: usize,
Are you sure? This is a parameter of the private method.

2023-09-12 08:09 UTC, stormshield-kg commented on src/theme/mod.rs
> +        bytes_pos: usize,
It is breaking since this is a public trait method. I have updated the changelog.

2023-09-12 08:24 UTC, pksunkara approved these changes

2023-09-12 08:31 UTC, merged